version: "3.1"
services:
  db:
    image: mongo:latest
    restart: always
    env_file:
      - ./.env/db.env
    ports:
      - 27017:27017
    volumes:
      - ./.data/db:/data/db
  service:
    build: ./service
    image: event-service
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env/service.env
    ports:
      - 3000:3000
