version: "3.1"
services:
  db:
    image: mongo:latest
    restart: always
    volumes:
      - ./.data/db:/data/db
  service:
    image: walenpiotr/events-solution-service:1.0.0
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env/service.env
    ports:
      - 4000:4000
  client:
    image: walenpiotr/events-solution-client:1.0.3
    restart: always
    ports:
      - 3999:80
